version: '3.5'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${DATA_PATH_HOST}:/var/lib/mysql
      - ${INIT_SQL_HOST}:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    privileged: true
    command:
      # setting mysql
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --init-file /data/application/init.sql
    networks:
      - movie-server

#
#  movie_service:
#    build:
#      context: ./
#    container_name: movie-server
#    ports:
#      - ${SERVER_PORT}:${SERVER_PORT}
#    restart: always
#    privileged: true
#    networks:
#      - movie-server

networks:
  movie-server:
    driver: ${NETWORKS_DRIVER}