apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: NodePort
  selector:
    app: movie-server
  ports:
    - port: 8000
      targetPort: movie-port
      nodePort: 30300
      protocol: TCP
