// Code generated by goctl. DO NOT EDIT!

package post

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{})
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "`post_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	postsRowsWithPlaceHolder = strings.Join(stringx.Remove(postsFieldNames, "`post_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	postsFieldNamesWithCommentCount          = builder.RawFieldNames(&PostWithCommentCount{})
	postsRowsWithCommentCount                = strings.Join(postsFieldNamesWithCommentCount, ",")
	postsRowsExpectAutoSetWithCommentCount   = strings.Join(stringx.Remove(postsFieldNamesWithCommentCount, "`post_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	postsRowsWithPlaceHolderWithCommentCount = strings.Join(stringx.Remove(postsFieldNamesWithCommentCount, "`post_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheMoviePostsPostIdPrefix = "cache:movie:posts:postId:"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, postId int64) (*Posts, error)
		Update(ctx context.Context, newData *Posts) error
		Delete(ctx context.Context, postId int64) error

		FindAllByCreateTime(ctx context.Context) ([]*Posts, error)
		//GetPostWithCommentsCountByCreateTime(ctx context.Context) ([]*PostWithCommentCount, error)
	}

	defaultPostsModel struct {
		sqlc.CachedConn
		table string
	}

	Posts struct {
		PostId     int64     `db:"post_id"`    // post id
		PostTitle  string    `db:"post_title"` // post title
		PostDesc   string    `db:"post_desc"`  // post desc
		UserId     int64     `db:"user_id"`    // who posted the post
		MovieId    int64     `db:"movie_id"`   // relevant movie info
		PostLike   int64     `db:"post_like"`  // post like
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}

	PostWithCommentCount struct {
		PostId     int64     `db:"post_id"`    // post id
		PostTitle  string    `db:"post_title"` // post title
		PostDesc   string    `db:"post_desc"`  // post desc
		UserId     int64     `db:"user_id"`    // who posted the post
		MovieId    int64     `db:"movie_id"`   // relevant movie info
		PostLike   int64     `db:"post_like"`  // post like
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`

		//Extra fields
		CommentCount int64 `db:"comment_count"`
	}
)

func newPostsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPostsModel {
	return &defaultPostsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`posts`",
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, postId int64) error {
	moviePostsPostIdKey := fmt.Sprintf("%s%v", cacheMoviePostsPostIdPrefix, postId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, postId)
	}, moviePostsPostIdKey)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, postId int64) (*Posts, error) {
	moviePostsPostIdKey := fmt.Sprintf("%s%v", cacheMoviePostsPostIdPrefix, postId)
	var resp Posts
	err := m.QueryRowCtx(ctx, &resp, moviePostsPostIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, postId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	moviePostsPostIdKey := fmt.Sprintf("%s%v", cacheMoviePostsPostIdPrefix, data.PostId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, postsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PostTitle, data.PostDesc, data.UserId, data.MovieId, data.PostLike)
	}, moviePostsPostIdKey)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, data *Posts) error {
	moviePostsPostIdKey := fmt.Sprintf("%s%v", cacheMoviePostsPostIdPrefix, data.PostId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, postsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PostTitle, data.PostDesc, data.UserId, data.MovieId, data.PostLike, data.PostId)
	}, moviePostsPostIdKey)
	return err
}

func (m *defaultPostsModel) FindAllByCreateTime(ctx context.Context) ([]*Posts, error) {
	query := fmt.Sprintf("SELECT %v FROM %v ORDER BY create_time DESC", postsRows, m.table)
	var resp []*Posts
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, err
	default:
		return nil, err
	}
}

//func (m *defaultPostsModel) GetPostWithCommentsCountByCreateTime(ctx context.Context) ([]*PostWithCommentCount, error) {
//	query := fmt.Sprintf("SELECT %v FROM %v ORDER BY create_time DESC", postsRows, m.table)
//}

func (m *defaultPostsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMoviePostsPostIdPrefix, primary)
}

func (m *defaultPostsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
