name: Movie-Server_CI/CD
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Golang env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name : Server Build
        run: go build -v ./...

      - name: Server Test
        run : go test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set up aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name golang-movie-app \
          --deployment-group-name golang-movie-app-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
